name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    name: Build and analyze
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build ACProgressHUDExample
        run: |
          cd ACProgressHUDExample
          xcodebuild clean build analyze \
            -project ACProgressHUDExample.xcodeproj \
            -scheme ACProgressHUDExample \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: Package IPA
        run: |
          cd ACProgressHUDExample/build/Release-iphoneos
          mkdir Payload
          cp -r ACProgressHUDExample.app Payload/
          zip -r ACProgressHUDExample.ipa Payload/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ACProgressHUDExample-IPA
          path: |
            ACProgressHUDExample/build/Release-iphoneos/ACProgressHUDExample.ipa
            ACProgressHUDExample/build/Release-iphoneos/ACProgressHUDExample.app
