name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    name: Build and analyze
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build ACProgressHUDExample
        run: |
          cd ACProgressHUDExample
          xcodebuild clean build analyze \
            -project ACProgressHUDExample.xcodeproj \
            -scheme ACProgressHUDExample \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: Check Build Directory
        run: |
          echo "Checking build directory structure..."
          ls -R ACProgressHUDExample/build/

      - name: Package IPA
        run: |
          cd ACProgressHUDExample
          mkdir -p build/Release-iphoneos/Payload
          cp -r build/Release-iphoneos/ACProgressHUDExample.app build/Release-iphoneos/Payload/
          cd build/Release-iphoneos
          zip -r ACProgressHUDExample.ipa Payload/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ACProgressHUD-Build
          path: ACProgressHUDExample/build/
